-- Seed data: the 15 preventive services shown on the site.
-- Run after schema.sql:
--   mysql -u root -p dr_deleep_dental < db/seed.sql

USE dr_deleep_dental;

TRUNCATE TABLE services;

INSERT INTO services (icon, title, teaser, duration, ideal_for, description, benefits, steps, sort_order, active) VALUES
  ('🦷', 'Dental Checkup', 'A full mouth review to catch issues early.', '20–30 min', 'Everyone, every 6 months', 'A dental checkup is a routine top-to-bottom look at your teeth, gums, bite and jaw. Dr. Deleep examines each tooth, checks for early decay or wear, and reviews your gum health so nothing gets missed between visits.', '["Catches decay and gum issues while they\'re still small and simple to treat", "Builds a baseline record so changes are spotted early", "A chance to ask questions about anything you\'ve noticed"]', '["Quick chat about any symptoms or concerns", "Visual and tactile exam of every tooth and gum surface", "Notes on anything to watch or treat, explained in plain language"]', 0, 1),
  ('✨', 'Teeth Cleaning', 'Professional cleaning for a fresher, healthier mouth.', '30–40 min', 'Everyone, every 6 months', 'A thorough professional clean that removes the plaque and surface staining daily brushing can\'t fully reach — leaving teeth smoother, brighter and less prone to buildup.', '["Reduces bad breath and surface staining", "Lowers the risk of cavities and gum inflammation", "Leaves teeth feeling noticeably smoother"]', '["Removal of plaque and light buildup around the gumline", "Cleaning between and along tooth surfaces", "Rinse and a quick check of the result"]', 1, 1),
  ('🪥', 'Scaling', 'Removes hardened deposits along the gumline.', '30–45 min', 'Anyone with visible tartar or gum sensitivity', 'Scaling uses fine instruments to gently remove hardened deposits (tartar) that have built up along and just below the gumline — deposits brushing alone cannot remove once they\'ve hardened.', '["Helps stop early gum disease from progressing", "Reduces gum bleeding and tenderness over time", "Makes future cleanings faster and easier"]', '["Gum and tartar assessment", "Careful removal of tartar deposits along the gumline", "Smoothing the tooth surface so plaque collects less easily"]', 2, 1),
  ('💎', 'Polishing', 'Smooths and brightens the tooth surface after cleaning.', '10–15 min', 'Usually paired with a cleaning or scaling visit', 'A finishing step after cleaning or scaling — a soft polishing paste smooths the tooth surface, lifts light surface stains, and makes it harder for new plaque to stick.', '["Visibly brighter, smoother teeth", "Slows how quickly new plaque re-forms", "A comfortable, quick finishing step"]', '["Polishing paste applied with a soft rotating tip", "Every surface buffed smooth", "Rinse and final check"]', 3, 1),
  ('🛡️', 'Fluoride Treatment', 'Strengthens enamel and helps prevent decay.', '10–15 min', 'Both children and adults, especially cavity-prone patients', 'A concentrated fluoride application is placed on the teeth to strengthen enamel and make it more resistant to the acids that cause cavities.', '["Strengthens weak spots in enamel before they become cavities", "Reduces sensitivity to hot and cold", "Extra protection for children\'s developing teeth"]', '["Teeth are dried and isolated", "Fluoride gel or varnish applied for a few minutes", "Brief wait before eating or drinking, as advised"]', 4, 1),
  ('🔒', 'Dental Sealants', 'A protective coating for cavity-prone back teeth.', '20–30 min', 'Children and teens, and adults with deep-grooved molars', 'A thin protective coating is bonded into the deep grooves of back teeth — the spots that are hardest to brush thoroughly and where cavities most often start.', '["Seals off grooves where food and plaque get trapped", "Painless and takes effect immediately", "Can last several years with normal wear"]', '["Tooth surface cleaned and dried", "Sealant material painted into the grooves", "Light-cured to harden it in place"]', 5, 1),
  ('💬', 'Oral Hygiene Consultation', 'Personalised guidance on your daily care routine.', '15–20 min', 'Anyone wanting a routine check-in on technique', 'A one-on-one session reviewing how you brush, floss and care for your teeth at home — with specific, practical adjustments for your mouth rather than generic advice.', '["Corrects small technique habits that cause big problems over time", "Product guidance tailored to your needs (soft brush, interdental brushes, etc.)", "A chance to ask anything about day-to-day care"]', '["Review of current brushing and flossing habits", "Hands-on tips for problem areas", "A simple routine to follow going forward"]', 6, 1),
  ('🔍', 'Oral Cancer Screening', 'Routine check for early warning signs.', '10 min', 'Adults, recommended annually', 'A quick, non-invasive visual and physical check of the lips, cheeks, tongue, and throat for anything unusual — an important routine screening that takes only a few minutes.', '["Early detection makes a significant difference in outcomes", "Quick, painless and non-invasive", "Peace of mind as part of a regular checkup"]', '["Visual examination of soft tissue in the mouth and throat", "Gentle feel for any unusual lumps or texture changes", "Any finding explained clearly, with next steps if needed"]', 7, 1),
  ('🧽', 'Plaque Removal', 'Clears soft buildup before it hardens into tartar.', '20–30 min', 'Anyone due for a routine clean', 'Targeted removal of the soft, sticky plaque film that forms daily on teeth — caught before it has a chance to harden into tartar.', '["Prevents plaque from progressing into harder-to-remove tartar", "Reduces risk of gum irritation", "Leaves your mouth feeling genuinely clean"]', '["Plaque highlighted and located", "Removed from all tooth surfaces, including between teeth", "Rinse and final check"]', 8, 1),
  ('⚙️', 'Tartar Removal', 'Removes hardened plaque that brushing can\'t reach.', '30–40 min', 'Anyone with visible or felt tartar buildup', 'Once plaque hardens into tartar, only a dental instrument can safely remove it. This treatment clears existing tartar deposits above and below the gumline.', '["Removes what brushing physically cannot", "Reduces gum inflammation caused by tartar irritation", "Freshens breath and improves the look of teeth near the gumline"]', '["Assessment of tartar location and extent", "Careful mechanical removal with dental instruments", "Smoothing and a final rinse"]', 9, 1),
  ('🍃', 'Cavity Prevention', 'Proactive steps to keep decay from starting.', '20–30 min', 'Everyone, especially those with a history of cavities', 'A preventive-focused visit combining a decay risk check with practical steps — diet notes, fluoride, or sealants — chosen specifically to reduce your chances of a future cavity.', '["Addresses your specific risk factors, not generic advice", "Combines the right mix of prevention tools for your mouth", "Often costs far less than treating a cavity later"]', '["Risk areas identified during examination", "Preventive treatment recommended and explained", "Simple habits suggested to reduce risk going forward"]', 10, 1),
  ('❤️', 'Gum Health Check', 'Assesses gums for early signs of disease.', '15–20 min', 'Everyone, especially if gums bleed or feel tender', 'A focused assessment of your gums — checking for bleeding, recession, pocket depth and inflammation — the early signs of gum disease, which is often painless until it\'s advanced.', '["Catches gum disease at its most treatable stage", "Explains what bleeding or sensitivity actually means", "Sets a clear plan if any treatment is needed"]', '["Gentle examination of gum tissue around each tooth", "Measurement of any gum pockets, if needed", "Clear explanation of findings and any next step"]', 11, 1),
  ('📐', 'Bite Examination', 'Checks how your teeth align and meet.', '15–20 min', 'Anyone with jaw pain, clicking, or uneven wear', 'An assessment of how your upper and lower teeth meet when you bite and chew — useful for jaw discomfort, clicking, headaches, or teeth that seem to be wearing unevenly.', '["Identifies alignment issues before they cause bigger wear or pain", "Explains the likely cause of clicking or jaw tension", "Guides whether further treatment is worth considering"]', '["Observation of how your teeth meet and move", "Check for wear patterns, clicking or discomfort", "Explanation of findings and any recommended next step"]', 12, 1),
  ('📅', 'Regular Dental Screening', 'Scheduled check-ins to track your oral health over time.', '20 min', 'Anyone on a recall/maintenance schedule', 'A scheduled follow-up visit that tracks changes since your last appointment, so small shifts in your oral health are noticed while they\'re still easy to manage.', '["Builds a clear picture of your oral health over time", "Makes each future visit faster and more predictable", "Keeps small issues from becoming big ones"]', '["Quick review of any changes since your last visit", "Standard examination of teeth and gums", "Notes added to your ongoing record"]', 13, 1),
  ('🧒', 'Children\'s Preventive Dental Care', 'Gentle, age-appropriate care to build healthy habits early.', '20–30 min', 'Children, from first teeth through the teenage years', 'A friendly, unhurried visit designed around kids — checking developing teeth, applying protective treatments where useful, and building positive associations with the dentist early on.', '["Catches developmental issues while they\'re easiest to address", "Sets up lifelong comfort with dental visits", "Combines naturally with fluoride and sealants when appropriate"]', '["Gentle, friendly examination at the child\'s pace", "Explanation for parents on what to watch for at home", "Preventive treatment offered if it would help"]', 14, 1);
